/* tslint:disable */
/* eslint-disable */
/**
 * Контракт для ОП
 * API для работы с заданиями и тетрадками для нашего маленького (пока ещё!) подобия Stepik. Здесь находится наш скромный функционал, выраженный в возможности создать новые задания, получить всю возможную информацию об уже имеющемся задании по его идентификатору, а также тут происходит связь \"учитель - студент\", когда ученик высылает своё решение (также по идентификатору).
 *
 * The version of the OpenAPI document: Pre-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatsData
 */
export interface ChatsData {
    /**
     * 
     * @type {string}
     * @memberof ChatsData
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatsData
     */
    summary?: string;
}

/**
 * Check if a given object implements the ChatsData interface.
 */
export function instanceOfChatsData(value: object): value is ChatsData {
    return true;
}

export function ChatsDataFromJSON(json: any): ChatsData {
    return ChatsDataFromJSONTyped(json, false);
}

export function ChatsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatsData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'summary': json['summary'] == null ? undefined : json['summary'],
    };
}

export function ChatsDataToJSON(json: any): ChatsData {
    return ChatsDataToJSONTyped(json, false);
}

export function ChatsDataToJSONTyped(value?: ChatsData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'summary': value['summary'],
    };
}

