/* tslint:disable */
/* eslint-disable */
/**
 * Контракт для ОП
 * API для работы с заданиями и тетрадками для нашего маленького (пока ещё!) подобия Stepik. Здесь находится наш скромный функционал, выраженный в возможности создать новые задания, получить всю возможную информацию об уже имеющемся задании по его идентификатору, а также тут происходит связь \"учитель - студент\", когда ученик высылает своё решение (также по идентификатору).
 *
 * The version of the OpenAPI document: Pre-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentData
 */
export interface CommentData {
    /**
     * 
     * @type {string}
     * @memberof CommentData
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentData
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentData
     */
    type?: string;
}

/**
 * Check if a given object implements the CommentData interface.
 */
export function instanceOfCommentData(value: object): value is CommentData {
    return true;
}

export function CommentDataFromJSON(json: any): CommentData {
    return CommentDataFromJSONTyped(json, false);
}

export function CommentDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentData {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function CommentDataToJSON(json: any): CommentData {
    return CommentDataToJSONTyped(json, false);
}

export function CommentDataToJSONTyped(value?: CommentData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
        'type': value['type'],
    };
}

