/* tslint:disable */
/* eslint-disable */
/**
 * Контракт для ОП
 * API для работы с заданиями и тетрадками для нашего маленького (пока ещё!) подобия Stepik. Здесь находится наш скромный функционал, выраженный в возможности создать новые задания, получить всю возможную информацию об уже имеющемся задании по его идентификатору, а также тут происходит связь \"учитель - студент\", когда ученик высылает своё решение (также по идентификатору).
 *
 * The version of the OpenAPI document: Pre-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageData
 */
export interface MessageData {
    /**
     * 
     * @type {string}
     * @memberof MessageData
     */
    role?: string;
    /**
     * 
     * @type {string}
     * @memberof MessageData
     */
    content?: string;
}

/**
 * Check if a given object implements the MessageData interface.
 */
export function instanceOfMessageData(value: object): value is MessageData {
    return true;
}

export function MessageDataFromJSON(json: any): MessageData {
    return MessageDataFromJSONTyped(json, false);
}

export function MessageDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageData {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'] == null ? undefined : json['role'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function MessageDataToJSON(json: any): MessageData {
    return MessageDataToJSONTyped(json, false);
}

export function MessageDataToJSONTyped(value?: MessageData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'content': value['content'],
    };
}

