/* tslint:disable */
/* eslint-disable */
/**
 * Контракт для ОП
 * API для работы с заданиями и тетрадками для нашего маленького (пока ещё!) подобия Stepik. Здесь находится наш скромный функционал, выраженный в возможности создать новые задания, получить всю возможную информацию об уже имеющемся задании по его идентификатору, а также тут происходит связь \"учитель - студент\", когда ученик высылает своё решение (также по идентификатору).
 *
 * The version of the OpenAPI document: Pre-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterData
 */
export interface RegisterData {
    /**
     * 
     * @type {string}
     * @memberof RegisterData
     */
    fullName: string;
    /**
     * Имя пользователя
     * @type {string}
     * @memberof RegisterData
     */
    username: string;
    /**
     * Пароль пользователя
     * @type {string}
     * @memberof RegisterData
     */
    password: string;
}

/**
 * Check if a given object implements the RegisterData interface.
 */
export function instanceOfRegisterData(value: object): value is RegisterData {
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function RegisterDataFromJSON(json: any): RegisterData {
    return RegisterDataFromJSONTyped(json, false);
}

export function RegisterDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterData {
    if (json == null) {
        return json;
    }
    return {
        
        'fullName': json['full_name'],
        'username': json['username'],
        'password': json['password'],
    };
}

export function RegisterDataToJSON(json: any): RegisterData {
    return RegisterDataToJSONTyped(json, false);
}

export function RegisterDataToJSONTyped(value?: RegisterData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'full_name': value['fullName'],
        'username': value['username'],
        'password': value['password'],
    };
}

