/* tslint:disable */
/* eslint-disable */
/**
 * Контракт для ОП
 * API для работы с заданиями и тетрадками для нашего маленького (пока ещё!) подобия Stepik. Здесь находится наш скромный функционал, выраженный в возможности создать новые задания, получить всю возможную информацию об уже имеющемся задании по его идентификатору, а также тут происходит связь \"учитель - студент\", когда ученик высылает своё решение (также по идентификатору).
 *
 * The version of the OpenAPI document: Pre-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SolutionsData
 */
export interface SolutionsData {
    /**
     * 
     * @type {number}
     * @memberof SolutionsData
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SolutionsData
     */
    author?: string;
    /**
     * 
     * @type {string}
     * @memberof SolutionsData
     */
    status?: string;
}

/**
 * Check if a given object implements the SolutionsData interface.
 */
export function instanceOfSolutionsData(value: object): value is SolutionsData {
    return true;
}

export function SolutionsDataFromJSON(json: any): SolutionsData {
    return SolutionsDataFromJSONTyped(json, false);
}

export function SolutionsDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolutionsData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'author': json['author'] == null ? undefined : json['author'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function SolutionsDataToJSON(json: any): SolutionsData {
    return SolutionsDataToJSONTyped(json, false);
}

export function SolutionsDataToJSONTyped(value?: SolutionsData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'author': value['author'],
        'status': value['status'],
    };
}

