/* tslint:disable */
/* eslint-disable */
/**
 * Контракт для ОП
 * API для работы с заданиями и тетрадками для нашего маленького (пока ещё!) подобия Stepik. Здесь находится наш скромный функционал, выраженный в возможности создать новые задания, получить всю возможную информацию об уже имеющемся задании по его идентификатору, а также тут происходит связь \"учитель - студент\", когда ученик высылает своё решение (также по идентификатору).
 *
 * The version of the OpenAPI document: Pre-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubtaskData
 */
export interface SubtaskData {
    /**
     * 
     * @type {number}
     * @memberof SubtaskData
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SubtaskData
     */
    text?: string;
}

/**
 * Check if a given object implements the SubtaskData interface.
 */
export function instanceOfSubtaskData(value: object): value is SubtaskData {
    return true;
}

export function SubtaskDataFromJSON(json: any): SubtaskData {
    return SubtaskDataFromJSONTyped(json, false);
}

export function SubtaskDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubtaskData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function SubtaskDataToJSON(json: any): SubtaskData {
    return SubtaskDataToJSONTyped(json, false);
}

export function SubtaskDataToJSONTyped(value?: SubtaskData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'text': value['text'],
    };
}

