server_port: 5000
prometheus_port: 5001

api_schema_path: spec.yml

gpt:
  url: https://caila.io/api/adapters/openai
  model:
  token:

database:
  engine: postgresql
  user:
  password:
  host:
  port:
  dbname:

logging:
    graylog:
      host: 0.0.0.0
      port: 9000
      enabled: false
      udp: true
    console:
      enabled: false
    root_level: INFO
    levels:
      httpx: WARN
      openai: WARN
      uvicorn.access: WARN
